import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Veg',
    color: Colors.purple,
    url:
        "https://media.easemytrip.com/media/Blog/India/636977607425696252/636977607425696252QYiiUU.jpg",
  ),
  Category(
    id: 'c2',
    title: 'Non-Veg',
    color: Colors.red,
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZNXGJyuLhUR9Zj7pVIA7CZbpdbSfbur456A&usqp=CAU",
  ),
  Category(
    id: 'c3',
    title: 'Shakes',
    color: Colors.orange,
    url:
        "https://lh3.googleusercontent.com/L0bi82LPD3vrht9vJxuadxQ_Iw9GRpg33Jpvv6x--zPCiCltbol9JkP7iS5NPIL4FH156yQAn6TLeihv0dogUHtKY-c=w800",
  ),
  Category(
    id: 'c4',
    title: 'Chinese',
    color: Colors.amber,
    url:
        "https://previews.123rf.com/images/espies/espies1904/espies190400167/121497887-manchurian-hakka-schezwan-noodles-popular-indochinese-food-served-in-a-bowl-selective-focus.jpg",
  ),
  Category(
    id: 'c5',
    title: 'Dessert',
    color: Colors.blue,
    url:
        "https://c.ndtvimg.com/2020-04/chd4rs3g_dessert_625x300_07_April_20.jpg",
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
    url:
        "https://ministryofcurry.com/wp-content/uploads/2018/03/fullsizeoutput_b6b2-e1536508128253.jpeg",
  ),
  // Category(
  //   id: 'c7',
  //   title: 'Breakfast',
  //   color: Colors.lightBlue,
  // ),
  // Category(
  //   id: 'c8',
  //   title: 'Asian',
  //   color: Colors.lightGreen,
  // ),
  // Category(
  //   id: 'c9',
  //   title: 'French',
  //   color: Colors.pink,
  // ),
  // Category(
  //   id: 'c10',
  //   title: 'Summer',
  //   color: Colors.teal,
  // ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      //'c2',
    ],
    title: 'Paneer Pakoda',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        "https://135700-392364-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2016/03/paneer-pakora-recipe-a.jpg",
    duration: 50,
    ingredients: [
      "Paneer, Besan",
      "Cooking Oil",
      "Basic Indian Spices",
      "Tomato Sauce",
      "Water",
    ],
    steps: [
      "1. Firstly, in a large mixing bowl take 1 tsp ginger garlic paste, ½ tsp chilli powder, ¾ tsp chaat masala, 1 tsp kasuri methi and ¼ tsp salt.",
      "2. Combine well forming a paste. Now add 9 cubes paneer and rub gently covering masala paste to paneer. keep aside.",
      "3. Further, prepare besan batter by taking ¾ cup besan and 2 tbsp rice flour in a mixing bowl.",
      "4. Also add ¼ tsp turmeric, ¼ tsp chilli powder, ¼ tsp hing, ¼ tsp chaat masala and ¼ tsp salt. Combine all the ingredients well.",
      "5. Add in ½ cup water and whisk smooth. Also, add a pinch of baking soda and mix gently.",
      "6. Dip the marinated paneer into prepared besan batter and coat it completely.",
      "7. Furthermore, deep fry in hot oil till they turn golden brown.",
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    ytVideo: 'https://www.youtube.com/watch?v=NwUNbuFK2Ro',
  ),
  Meal(
    id: 'm2',
    categories: [
      'c1',
    ],
    title: 'Pav Bhaji',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToRfsVWy3Ym2q8Og3uyeAdZQ8JYbMSkUj9eA&usqp=CAU",
    duration: 60,
    ingredients: [
      "Mashed Potatoes, Butter",
      "Basic Indian Spices",
      "Ghee, Boiled Veggies",
      "Pavs, Cheese",
      "Amchur Powder",
    ],
    steps: [
      "1. firstly, in a pressure cooker heat butter and saute onions.also add ginger-garlic paste and saute.",
      "2. additionally, add capsicum and saute for a minute.furthermore, saute tomatoes till they turn soft and mushy.",
      "3. now add green peas, potato and saute for a minute.further, add chili powder, turmeric, pav bhaji masala and salt. saute well for a minute.",
      "4. also add 1.5 cups of water and mix well.cover and pressure cook for 3 whistles and mash all the vegetables well.",
      "5. optionally, add a tsp of butter for more flavours.now, heat tawa and add a tsp of butter and prepared pav bhaji.",
      "6. further, slit the pav in centre.spread and toast both the sides.finally, serve pav bhaji along with toasted pav",
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    ytVideo: 'http://youtube.com/watch?v=sAnPUIvPc1I',
  ),
  Meal(
    id: 'm3',
    categories: [
      'c2',
      //'c3',
    ],
    title: 'Chilli Chicken',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        "https://www.indianhealthyrecipes.com/wp-content/uploads/2018/07/chilli-chicken-recipe-500x500.jpg",
    duration: 70,
    ingredients: [
      "2 chicken breasts,1 teaspoon salt",
      "½ teaspoon pepper,1 egg, beaten",
      "¾ cup flour (100 g),1 green pepper, sliced",
      "1 red pepper, sliced,rice to serve",
      "3 cloves garlic cloves, crushed",
      "1 red chilli, chopped,3 tablespoons soy sauce",
      "2 tablespoons tomato puree,½ cup water (100 mL)",
    ],
    steps: [
      "1. Season the chicken with salt and pepper.Cut the chicken into thin strips then coat in the egg wash and flour.",
      "2. Shallow fry for a few minutes on each side, until golden brown.Add the peppers and fry for another couple of minutes.",
      "3. Remove the chicken and peppers and set aside.In the same pan, add the garlic, red chilli, soy sauce, tomato purée, and water. ",
      "4. Stir and simmer the mixture reduces and is thick and syrupy.",
      "5. Add back in the chicken and peppers and stir well in the sauce.Serve with rice.",
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    ytVideo: 'https://www.youtube.com/watch?v=pMCS1TR4Wyo',
  ),
  Meal(
    id: 'm4',
    categories: [
      'c2',
    ],
    title: 'Bhurji Pav',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        "https://im.whatshot.in/img/2019/Jul/shutterstock-1230805675-1562740202.jpg",
    duration: 60,
    ingredients: [
      "Eggs, Pav",
      "Butter, coriander",
      "Basic Indian Spices",
      "Oil",
      "Tomatoes And Onions",
    ],
    steps: [
      "1. Heat ghee in a frying pan.Add ginger, garlic ,green chilies and stir fry for half a minute.",
      "2. Add the chopped onions and fry .Next add the tomatoes, turmeric powder, chili powder, kitchen king masala and salt and fry for a couple of minutes till the tomatoes break down slightly. ",
      "3. Add the lightly whisked eggs and cook on medium heat, whisking to mix them well with the masala till they are cooked.",
      "4. Cook the eggs until just set.Add the butter and cheese, mix through and take off heat.",
      "5. Garnish with finely chopped fresh coriander and enjoy hot on toasted bread or between buttered pav buns or with paranthas.",
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    ytVideo: 'https://www.youtube.com/watch?v=7Uhp9mEAACc',
  ),
  Meal(
    id: 'm5',
    categories: [
      'c3'
      //    'c5',
      //'c10',
    ],
    title: 'Cad-M',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        "https://content3.jdmagicbox.com/comp/pune/y5/020pxx20.xx20.170211171719.m9y5/catalogue/cad-m-cad-b-dhankawadi-pune-home-delivery-restaurants-3pme0sf.jpg",
    duration: 35,
    ingredients: [
      "Dark Chocolate",
      "Milk, Sugar",
      "Cadbury, Ice",
      "Chocolate Ice Cream",
    ],
    steps: [
      "1. Melt chocolate in 1 cup of milk on low flame.Stir the milk to melt all the chocolate.",
      "2. Once the chocolate melts, turn off the flame and let it cool.",
      "3. After 30mins, transfer the thick sauce in a grinder jar along with a scoop of dark chocolate ice cream.",
      "4. Pulse it until frothy and smooth.Use Blender",
      "5. Transfer it to serving glass and top it with ice cream.Keep this glass in the freezer and let it set for 1 hour.",
      "6. After 1 hour, grate chocolate on the top and serve immediately.",
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
    ytVideo: 'https://www.youtube.com/watch?v=ZM1UX82NyUA',
  ),
  Meal(
    id: 'm6',
    categories: [
      'c3',
      //'c10',
    ],
    title: 'Oreo Shake',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        "https://i.pinimg.com/originals/e4/0e/9f/e40e9fc6162274b3e8ab2f4a36459332.jpg",
    duration: 40,
    ingredients: [
      "Hersheys Syrup",
      "Oreo Biscuits",
      "Water(Ice), Sugar",
      "Milk",
      "Vanila Ice cream",
    ],
    steps: [
      "1. Place the vanilla ice cream, milk, 8 Oreo cookies, and the chocolate sauce in a blender and puree until smooth.",
      "2. Crush the remaining Oreo cookies evenly",
      "3. Pour the milkshakes into two tall glasses and top each with the crushed Oreo cookie crumbs. Garnish with a straw.",
      "4. Also add chocolate sauce for garnishing",
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    ytVideo: 'https://www.youtube.com/watch?v=0pyMDMAjVc0',
  ),
  Meal(
    id: 'm7',
    categories: [
      'c4',
    ],
    title: 'Veg Noodles',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        "https://i2.wp.com/vegecravings.com/wp-content/uploads/2017/03/veg-hakka-noodles-recipe-with-step-by-step-instructions.jpg?fit=1838%2C1493&quality=65&strip=all&ssl=1",
    duration: 25,
    ingredients: [
      "Water, Oil, Salt",
      "Vinegar, Noddles",
      "Basic Indian Spices",
      "Soya Sauce",
      "Tomato Ketchup",
      "Veggies Including Capsicum, Cabbage, Carrot",
      "¼ tsp pepper powder",
    ],
    steps: [
      "1. take 6 cup water, 1 tsp salt and 1 tsp oil.once the water comes to a boil place a pack of hakka noodles ",
      "2. boil the noodles for 3 minutes,drain off the water from noodles and pour 1 cup of cold water to prevent from further cooking.",
      "3. Add oil,saute ½ onion, 2 tbsp spring onion on high flame.further add Veggies and saute them",
      "4. stir fry on high flame for 2 minutes or until veggies are cooked yet retain their crunch.",
      "5. further add 2 tbsp tomato sauce, 1 tbsp soy sauce, 1 tbsp vinegar, 1 tbsp chilli sauce, ¼ tsp pepper powder and ½ tsp salt.",
      "6. stir fry until sauces are well combined.add in boiled noodles and mix gently.",
      "7. toss and mix until noodles are cooked completely.finally, garnish with spring onion and enjoy veg noodles.",
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    ytVideo: 'https://www.youtube.com/watch?v=7kwmmK4FhCI',
  ),
  Meal(
    id: 'm8',
    categories: [
      'c4',
    ],
    title: 'Garlic Chicken',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        "https://www.jocooks.com/wp-content/uploads/2013/05/honey-garlic-chicken-wings-1-7.jpg",
    duration: 60,
    ingredients: [
      "500 grams chicken small pieces,3 tablespoons garlic",
      "2 medium onions, 1 small tomato",
      "1 tablespoon crushed dry chillies,2 green chillies",
      "1 tablespoon vinegar, salt",
      "1/2 teaspoon sugar spring onions",
    ],
    steps: [
      "1. Lightly crush the garlic. Marinate the chicken pieces with the crushed dry chillies, vinegar, garlic and salt.",
      "2. Mix well, Heat some oil in a thick-bottomed pan. Add chopped onions and cook on a medium flame ",
      "3. When the onions start turning brown, add the chopped tomatoes, and cook further.",
      "4. Cook on a low flame till the onion and tomato mix reach a thick paste like consistency. Add salt, sugar, and 3 tablespoons of water.",
      "5. Combine well. Switch off when the water start to disappear.Transfer the contents to a bowl.",
      "6. add a little oil, and braise the marinated chicken on a high flame.Stir occasionally and fry for a couple of minutes. ",
      "7. add the onion-tomato paste back to the pan, mix well, and cook on a low flame.",
      "8. Cook till chicken pieces is evenly coated. Add the chopped green chillies, and a tablespoon of finely chopped spring onions.",
      "9. Combine well. Cook for a couple of minutes, and switch off.Garnish with spring onions, and serve hot.",
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    ytVideo: 'https://www.youtube.com/watch?v=o573s6278VA',
  ),
  Meal(
    id: 'm9',
    categories: [
      'c5',
    ],
    title: 'Samoa Lasagna',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        "https://hips.hearstapps.com/hmg-prod/images/20200205-samoa-dessert-lasagna-ehg-9775-jpg-1582826733.jpg",
    duration: 45,
    ingredients: [
      "1 1/2 c. crushed Nilla wafers.1/2 c. toasted shredded coconut",
      "6 tbsp. melted butter.1 (10.4-oz.) jar caramel",
      "(3.9-oz.) boxes instant chocolate pudding",
      "cold milk,heavy cream",
      "8-oz.) block cream cheese, softened1/2 c. powdered sugar",
      "toasted, sweetened coconut flakes1/2 c. chocolate chips, melted",
      "Caramel, warmed, for drizzling",
    ],
    steps: [
      "1. Preheat oven to 350°. In a medium bowl, combine crushed Nillas, coconut, and melted butter.",
      "2. Press into the bottom of a 9”-x-13” baking dish and bake until golden, 10 to 12 minutes. Let cool. ",
      "3. Pour caramel over cooled crust and spread into an even layer.",
      "4. In another medium bowl, combine pudding mix and milk; whisk until thickened. Pour over caramel and smooth into an even layer. ",
      "5. In a large bowl, beat heavy cream into stiff peaks. In a medium bowl, beat cream cheese and powdered sugar until no lumps remain, then fold in whipped cream.",
      "6. Spoon mixture over pudding and smooth into an even layer. Refrigerate until well chilled, at least 2 hours.",
      "7. When ready to serve, top with toasted coconut and drizzle with melted chocolate and caramel.",
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    ytVideo: 'https://www.youtube.com/watch?v=HBym9dDya-k',
  ),
  Meal(
    id: 'm10',
    categories: [
      //'c2',
      'c5',
      //'c10',
    ],
    title: 'Oreo Truffles',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/delish-oreo-truffles-094-1544218913.jpg?crop=0.668xw:1.00xh;0.191xw,0&resize=480:*",
    duration: 45,
    ingredients: [
      "Oreos",
      "Cream cheese",
      "Chocolate melts ",
      "Heshey's Syrup",
      "Sugar",
    ],
    steps: [
      "1. Line an 18 by 13-inch baking sheet with wax paper or parchment paper.",
      "2. Place 36 Oreos in a food processor (entire cookie, don’t remove cream filling) and pulse too fine crumbs. ",
      "3. add cream cheese to food processor, pulse in bursts until mixture is combined",
      "4. Scoop mixture out about 1 Tbsp at a time and form into 1 inch balls then align on prepared cookie sheet.",
      "5. Place truffles in freezer for 15 minutes. Meanwhile crush remaining 3 Oreos.",
      "6. Melt almond bark or chocolate according to directions on package.",
      "7. Remove truffles from freezer and dip in melted chocolate",
      "8. Return to baking sheet, immediately sprinkle tops with crushed Oreos if desired, then allow chocolate to set.",
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    ytVideo: 'https://www.youtube.com/watch?v=vaNR38cbdnk',
  ),
  Meal(
    id: 'm11',
    categories: [
      //'c2',
      'c6',
      //'c10',
    ],
    title: 'Puran Poli',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/08/puran-poli.jpg",
    duration: 240,
    ingredients: [
      "1 cup blanched chana dal,2 tablespoon ghee",
      "1/2 teaspoon fennel seeds powder,1 cup all purpose flour",
      "1 cup powdered jaggery,oil,1 teaspoon powdered green cardamom",
      "1 teaspoon nutmeg powder,1/4 teaspoon turmeric",
      "1/4 cup water",
    ],
    steps: [
      "1. Put a saucepan over medium flame and add ghee in it. Once the ghee is melted, add blanched dal in it. Roast for 2-3 minutes and then add jaggery, ginger powder, cardamom powder, fennel powder and nutmeg powder in it.",
      "2. Mix all the ingredients and cook the dal for another 2-3 minutes.",
      "3. add all-purpose flour, turmeric, salt to taste and refined oil. Rub well and then add a little water at a time and knead well to make a stiff dough. ",
      "4. Take one part and press it a little to make space in the centre. Once done, take the chana-jaggery mixture and fill it in the centre. Close and shape again like a ball.",
      "5. Grease your hands a little and make roti with your hands. ",
      "6. Put a tawa on medium flame and place the roti on it. Add 1/2 teaspoon ghee and cook well from both sides. Serve hot and pair with tea or coffee.",
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    ytVideo: 'https://www.youtube.com/watch?v=zZ_jUpD2gR0',
  ),
  Meal(
    id: 'm12',
    categories: [
      //'c2',
      'c6',
      //'c10',
    ],
    title: 'Ras Malai',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        "https://aromaticessence.co/wp-content/uploads/2018/05/49E95995-028D-44D2-9252-2CDA545120D8.jpeg",
    duration: 180,
    ingredients: [
      "2 litre milk,2 tbsp lemon juice,1 cup water",
      "1 cup sugar,½ tsp cardamom powder",
      "2 tbsp saffron milk,7 pistachios,",
      "5 almonds, chopped,10 cashews",
    ],
    steps: [
      "1. firstly, boil milk.additionally, add lemon juice and stir till milk curdles completely.",
      "2. drain the curdled milk and squeeze off excess water.after 30 minutes, start to knead the paneer for 10 minutes.",
      "3. furthermore, make small balls and flatten. keep aside.",
      "4. For sugar-firstly, take sugar and water.boil the syrup for 10 minutes.after that, drop the prepared paneer balls.",
      "5. cover and boil for 15 minutes.furthermore, squeeze of sugar syrup.",
      "6. For Rabri-firstly, heat milk and get to a boil.once a layer of cream is formed over the milk, stick it to sides of vessel.",
      "7. repeat the process for atleast 5 times or till milk reduces to one-third.further, add sugar, cardamom powder and saffron milk.",
      "8. give a good mix and get to boil.also scrape off the collected cream from sides. and give a good stir.further, refrigerate for 2-3 hours.",
      "9. For Ras Malai-firstly, pour the chilled rabri / rabdi over the squeezed paneer balls.",
      "10. finally garnish with few chopped nuts and allow to absorb for 2 hours.",
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    ytVideo: 'https://www.youtube.com/watch?v=LECpZPkP9Wk',
  ),
];
